### ISSUE TITLE
NoSuchFieldError mCtxPtr in 1.0.3

### ISSUE THREAD

**Issue by Pitel** [facebook/conceal#109]
I upgraded Conceal from 1.0.1 to 1.0.3 from mvnrepository
```
compile 'com.facebook.conceal:conceal:1.0.3@aar'
```

and now I'm getting this error:

```
D/dalvikvm( 3874): Trying to load lib /data/app-lib/cz.master.annie-1/libconceal.so 0x418b1f58
D/dalvikvm( 3874): Added shared lib /data/app-lib/cz.master.annie-1/libconceal.so 0x418b1f58
W/dalvikvm( 3874): JNI WARNING: JNI function FindClass called with exception pending
W/dalvikvm( 3874):              in Ljava/lang/Runtime;.nativeLoad:(Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/String;)Ljava/lang/String; (FindClass)
W/dalvikvm( 3874): Pending exception is:
I/dalvikvm( 3874): java.lang.NoSuchFieldError: no field with name='mCtxPtr' signature='J' in class Lcom/facebook/crypto/cipher/NativeGCMCipher;
I/dalvikvm( 3874): 	at java.lang.Runtime.nativeLoad(Native Method)
I/dalvikvm( 3874): 	at java.lang.Runtime.doLoad(Runtime.java:421)
I/dalvikvm( 3874): 	at java.lang.Runtime.loadLibrary(Runtime.java:362)
I/dalvikvm( 3874): 	at java.lang.System.loadLibrary(System.java:555)
I/dalvikvm( 3874): 	at com.facebook.crypto.util.SystemNativeCryptoLibrary.loadLibraries(SystemNativeCryptoLibrary.java:50)
I/dalvikvm( 3874): 	at com.facebook.crypto.util.SystemNativeCryptoLibrary.ensureCryptoLoaded(SystemNativeCryptoLibrary.java:39)
I/dalvikvm( 3874): 	at com.facebook.crypto.cipher.NativeGCMCipher.decryptInit(NativeGCMCipher.java:63)
I/dalvikvm( 3874): 	at com.facebook.crypto.CipherHelper.getCipherInputStream(CipherHelper.java:65)
I/dalvikvm( 3874): 	at com.facebook.crypto.Crypto.getCipherInputStream(Crypto.java:83)
I/dalvikvm( 3874): 	at cz.master.annie.utils.Utils.decryptConcealString(Utils.java:504)
I/dalvikvm( 3874): 	at cz.master.annie.ui.landingpage.ActivityMain.checkConceal(ActivityMain.java:298)
I/dalvikvm( 3874): 	at cz.master.annie.ui.landingpage.ActivityMain.onCreate(ActivityMain.java:145)
I/dalvikvm( 3874): 	at android.app.Activity.performCreate(Activity.java:5301)
I/dalvikvm( 3874): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
I/dalvikvm( 3874): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
I/dalvikvm( 3874): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
I/dalvikvm( 3874): 	at android.app.ActivityThread.access$1100(ActivityThread.java:143)
I/dalvikvm( 3874): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
I/dalvikvm( 3874): 	at android.os.Handler.dispatchMessage(Handler.java:102)
I/dalvikvm( 3874): 	at android.os.Looper.loop(Looper.java:136)
I/dalvikvm( 3874): 	at android.app.ActivityThread.main(ActivityThread.java:5398)
I/dalvikvm( 3874): 	at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm( 3874): 	at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm( 3874): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
I/dalvikvm( 3874): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
I/dalvikvm( 3874): 	at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 3874): "main" prio=5 tid=1 NATIVE
I/dalvikvm( 3874):   | group="main" sCount=0 dsCount=0 obj=0x415abd50 self=0x414e4700
I/dalvikvm( 3874):   | sysTid=3874 nice=-1 sched=0/0 cgrp=apps handle=1074041172
I/dalvikvm( 3874):   | state=R schedstat=( 0 0 0 ) utm=123 stm=11 core=0
I/dalvikvm( 3874):   #00  pc 000012f6  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
I/dalvikvm( 3874):   #01  pc 00060938  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+31)
I/dalvikvm( 3874):   #02  pc 00054930  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+395)
I/dalvikvm( 3874):   #03  pc 0005499e  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+25)
I/dalvikvm( 3874):   #04  pc 00038a7c  /system/lib/libdvm.so
I/dalvikvm( 3874):   #05  pc 00041a10  /system/lib/libdvm.so
I/dalvikvm( 3874):   #06  pc 0002d5b2  /data/app-lib/cz.master.annie-1/libconceal.so
I/dalvikvm( 3874):   #07  pc 0002d6e6  /data/app-lib/cz.master.annie-1/libconceal.so (JNI_OnLoad+37)
I/dalvikvm( 3874):   #08  pc 000502e6  /system/lib/libdvm.so (dvmLoadNativeCode(char const*, Object*, char**)+465)
I/dalvikvm( 3874):   #09  pc 00067bd0  /system/lib/libdvm.so
I/dalvikvm( 3874):   #10  pc 000272e0  /system/lib/libdvm.so
I/dalvikvm( 3874):   #11  pc 0002e290  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
I/dalvikvm( 3874):   #12  pc 0002b93c  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
I/dalvikvm( 3874):   #13  pc 00060b4c  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+391)
I/dalvikvm( 3874):   #14  pc 00068cae  /system/lib/libdvm.so
I/dalvikvm( 3874):   #15  pc 000272e0  /system/lib/libdvm.so
I/dalvikvm( 3874):   #16  pc 0002e290  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
I/dalvikvm( 3874):   #17  pc 0002b93c  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
I/dalvikvm( 3874):   #18  pc 0006086a  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+337)
I/dalvikvm( 3874):   #19  pc 00049f92  /system/lib/libdvm.so
I/dalvikvm( 3874):   #20  pc 000504d8  /system/lib/libandroid_runtime.so
I/dalvikvm( 3874):   #21  pc 0005124e  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*, bool)+357)
I/dalvikvm( 3874):   #22  pc 00001562  /system/bin/app_process
I/dalvikvm( 3874):   #23  pc 0000e620  /system/lib/libc.so (__libc_init+47)
I/dalvikvm( 3874):   at java.lang.Runtime.nativeLoad(Native Method)
I/dalvikvm( 3874):   at java.lang.Runtime.doLoad(Runtime.java:421)
I/dalvikvm( 3874):   at java.lang.Runtime.loadLibrary(Runtime.java:362)
I/dalvikvm( 3874):   at java.lang.System.loadLibrary(System.java:555)
I/dalvikvm( 3874):   at com.facebook.crypto.util.SystemNativeCryptoLibrary.loadLibraries(SystemNativeCryptoLibrary.java:50)
I/dalvikvm( 3874):   at com.facebook.crypto.util.SystemNativeCryptoLibrary.ensureCryptoLoaded(SystemNativeCryptoLibrary.java:39)
I/dalvikvm( 3874):   at com.facebook.crypto.cipher.NativeGCMCipher.decryptInit(NativeGCMCipher.java:63)
I/dalvikvm( 3874):   at com.facebook.crypto.CipherHelper.getCipherInputStream(CipherHelper.java:65)
I/dalvikvm( 3874):   at com.facebook.crypto.Crypto.getCipherInputStream(Crypto.java:83)
I/dalvikvm( 3874):   at cz.master.annie.utils.Utils.decryptConcealString(Utils.java:504)
I/dalvikvm( 3874):   at cz.master.annie.ui.landingpage.ActivityMain.checkConceal(ActivityMain.java:298)
I/dalvikvm( 3874):   at cz.master.annie.ui.landingpage.ActivityMain.onCreate(ActivityMain.java:145)
I/dalvikvm( 3874):   at android.app.Activity.performCreate(Activity.java:5301)
I/dalvikvm( 3874):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
I/dalvikvm( 3874):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
I/dalvikvm( 3874):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
I/dalvikvm( 3874):   at android.app.ActivityThread.access$1100(ActivityThread.java:143)
I/dalvikvm( 3874):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
I/dalvikvm( 3874):   at android.os.Handler.dispatchMessage(Handler.java:102)
I/dalvikvm( 3874):   at android.os.Looper.loop(Looper.java:136)
I/dalvikvm( 3874):   at android.app.ActivityThread.main(ActivityThread.java:5398)
I/dalvikvm( 3874):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm( 3874):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm( 3874):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
I/dalvikvm( 3874):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
I/dalvikvm( 3874):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 3874): 
E/dalvikvm( 3874): VM aborting
F/libc    ( 3874): Fatal signal 6 (SIGABRT) at 0x00000f22 (code=-6), thread 3874 (cz.master.annie)
D/TcpManager( 3874): TCP writing executed.
I/TcpManager( 3874): TCP HB sent.
I/DEBUG   (  196): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  196): Build fingerprint: 'Huawei/MediaPad/hwt1701:4.4.2/HuaweiMediaPad/T1701wV1R1C232B006:user/release-keys'
I/DEBUG   (  196): Revision: '0'
I/DEBUG   (  196): pid: 3874, tid: 3874, name: cz.master.annie  >>> cz.master.annie <<<
I/DEBUG   (  196): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
I/DEBUG   (  196):     r0 00000000  r1 00000f22  r2 00000006  r3 00000000
I/DEBUG   (  196):     r4 00000006  r5 00000016  r6 00000f22  r7 0000010c
I/DEBUG   (  196):     r8 624896c1  r9 00000000  sl 41591c74  fp 5bac124c
I/DEBUG   (  196):     ip 00000001  sp bea05118  lr 4007229d  pc 400811d8  cpsr 00070010
I/DEBUG   (  196):     d0  74726f6261204d56  d1  726174536576696e
I/DEBUG   (  196):     d2  6874654d24746975  d3  677241646e41646c
I/DEBUG   (  196):     d4  725f64696f72646e  d5  732e656d69746e75
I/DEBUG   (  196):     d6  6f72646e6128206f  d7  72646e413a3a6469
I/DEBUG   (  196):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  196):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  196):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  196):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  196):     d16 0000000000000000  d17 000000000000000e
I/DEBUG   (  196):     d18 00000000000000db  d19 0000000008000000
I/DEBUG   (  196):     d20 0000000000ffffff  d21 0000000000000000
I/DEBUG   (  196):     d22 0000000009000000  d23 0000000000000001
I/DEBUG   (  196):     d24 0000000000000000  d25 3fcef049fb9094d1
I/DEBUG   (  196):     d26 40026bb1bbb55516  d27 0000000000000002
I/DEBUG   (  196):     d28 ffffffffffffffff  d29 ffffffffffffffff
I/DEBUG   (  196):     d30 0000000000000001  d31 0000000005000002
I/DEBUG   (  196):     scr 60000010
I/DEBUG   (  196): 
I/DEBUG   (  196): backtrace:
I/DEBUG   (  196):     #00  pc 000221d8  /system/lib/libc.so (tgkill+12)
I/DEBUG   (  196):     #01  pc 00013299  /system/lib/libc.so (pthread_kill+48)
I/DEBUG   (  196):     #02  pc 000134ad  /system/lib/libc.so (raise+10)
I/DEBUG   (  196):     #03  pc 000121e1  /system/lib/libc.so
I/DEBUG   (  196):     #04  pc 00021a8c  /system/lib/libc.so (abort+4)
I/DEBUG   (  196):     #05  pc 00045f4b  /system/lib/libdvm.so (dvmAbort+78)
I/DEBUG   (  196):     #06  pc 00041a11  /system/lib/libdvm.so
I/DEBUG   (  196):     #07  pc 0002d5b5  /data/app-lib/cz.master.annie-1/libconceal.so
I/DEBUG   (  196):     #08  pc 0002d6e7  /data/app-lib/cz.master.annie-1/libconceal.so (JNI_OnLoad+38)
I/DEBUG   (  196):     #09  pc 000502e9  /system/lib/libdvm.so (dvmLoadNativeCode(char const*, Object*, char**)+468)
I/DEBUG   (  196):     #10  pc 00067bd1  /system/lib/libdvm.so
I/DEBUG   (  196):     #11  pc 000272e0  /system/lib/libdvm.so
I/DEBUG   (  196):     #12  pc 0002e290  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
I/DEBUG   (  196):     #13  pc 0002b93c  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
I/DEBUG   (  196):     #14  pc 00060b4d  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
I/DEBUG   (  196):     #15  pc 00068caf  /system/lib/libdvm.so
I/DEBUG   (  196):     #16  pc 000272e0  /system/lib/libdvm.so
I/DEBUG   (  196):     #17  pc 0002e290  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
I/DEBUG   (  196):     #18  pc 0002b93c  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
I/DEBUG   (  196):     #19  pc 0006086b  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+338)
I/DEBUG   (  196):     #20  pc 00049f93  /system/lib/libdvm.so
I/DEBUG   (  196):     #21  pc 000504db  /system/lib/libandroid_runtime.so
I/DEBUG   (  196):     #22  pc 0005124f  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*, bool)+358)
I/DEBUG   (  196):     #23  pc 00001563  /system/bin/app_process
I/DEBUG   (  196):     #24  pc 0000e623  /system/lib/libc.so (__libc_init+50)
I/DEBUG   (  196):     #25  pc 00000fd0  /system/bin/app_process
I/DEBUG   (  196): 
I/DEBUG   (  196): stack:
I/DEBUG   (  196):          bea050d8  62539045  /data/app-lib/cz.master.annie-1/libconceal.so
I/DEBUG   (  196):          bea050dc  00000000  
I/DEBUG   (  196):          bea050e0  00000001  
I/DEBUG   (  196):          bea050e4  624896c1  /data/app-lib/cz.master.annie-1/libconceal.so (JNI_OnLoad)
I/DEBUG   (  196):          bea050e8  00000000  
I/DEBUG   (  196):          bea050ec  41591c74  /system/lib/libdvm.so
I/DEBUG   (  196):          bea050f0  5bac124c  
I/DEBUG   (  196):          bea050f4  40085909  /system/lib/libc.so (snprintf+80)
I/DEBUG   (  196):          bea050f8  00000000  
I/DEBUG   (  196):          bea050fc  00000000  
I/DEBUG   (  196):          bea05100  bea05174  [stack]
I/DEBUG   (  196):          bea05104  00000000  
I/DEBUG   (  196):          bea05108  00000000  
I/DEBUG   (  196):          bea0510c  00000000  
I/DEBUG   (  196):          bea05110  00004000  
I/DEBUG   (  196):          bea05114  91d84ebe  
I/DEBUG   (  196):     #00  bea05118  00000006  
I/DEBUG   (  196):          bea0511c  00000016  
I/DEBUG   (  196):          bea05120  00000f22  
I/DEBUG   (  196):          bea05124  00000001  
I/DEBUG   (  196):          bea05128  00000001  
I/DEBUG   (  196):          bea0512c  4007229d  /system/lib/libc.so (pthread_kill+52)
I/DEBUG   (  196):     #01  bea05130  00000006  
I/DEBUG   (  196):          bea05134  62539045  /data/app-lib/cz.master.annie-1/libconceal.so
I/DEBUG   (  196):          bea05138  00000000  
I/DEBUG   (  196):          bea0513c  400724b1  /system/lib/libc.so (raise+14)
I/DEBUG   (  196):     #02  bea05140  bea0514c  [stack]
I/DEBUG   (  196):          bea05144  400711e5  /system/lib/libc.so
I/DEBUG   (  196): 
I/DEBUG   (  196): memory near r8:
I/DEBUG   (  196):     624896a0 4604b510 f0006840 6860ea24 e88af7ff  
I/DEBUG   (  196):     624896b0 f7ff6820 4620e888 4010e8bd bb4af0af  
I/DEBUG   (  196):     624896c0 a902b513 4a0f4c10 6824447c 93016823  
I/DEBUG   (  196):     624896d0 f8412300 68033d08 4798699b 9800b938  
I/DEBUG   (  196):     624896e0 fd7cf7ff f7ff9800 4806ff5b f04fe001  
I/DEBUG   (  196):     624896f0 9a0130ff 429a6823 f7ffd001 b002e858  
I/DEBUG   (  196):     62489700 bf00bd10 00010004 000d4420 47702001  
I/DEBUG   (  196):     62489710 47702000 f8d36803 47183194 f8d36803  
I/DEBUG   (  196):     62489720 471831b8 e92d43f0 e2538000 e24dd084  
I/DEBUG   (  196):     62489730 e1a06000 e1a05001 e1a04002 0a000074  
I/DEBUG   (  196):     62489740 e5903000 e1530008 0a000003 e2713001  
I/DEBUG   (  196):     62489750 33a03000 e1933fa2 1a00000c e3550000  
I/DEBUG   (  196):     62489760 e5868000 0286904c 0a000019 e1a00008  
I/DEBUG   (  196):     62489770 eb000edf e3500080 e1a07000 ca00005d  
I/DEBUG   (  196):     62489780 e1540007 ca000045 e3540080 9a000002  
I/DEBUG   (  196):     62489790 e3a00000 e28dd084 e8bd83f0 e1a02004  
I/DEBUG   (  196): 
I/DEBUG   (  196): memory near sl:
I/DEBUG   (  196):     41591c54 4159119c 41591210 4159124c 41538ba1  
I/DEBUG   (  196):     41591c64 4153bb25 41552e7d 4154f743 41510e20  
I/DEBUG   (  196):     41591c74 00000000 00000000 00000000 40087f31  
I/DEBUG   (  196):     41591c84 40087e35 400856fd 4009acfc 4009a3f8  
I/DEBUG   (  196):     41591c94 40099f50 4009a02c 4009b158 400c35f4  
I/DEBUG   (  196):     41591ca4 400c3250 400d3528 400d3514 400d34ec  
I/DEBUG   (  196):     41591cb4 400d32a8 4009a9cc 4009a9b8 4009a990  
I/DEBUG   (  196):     41591cc4 400d32e8 40080bc0 4009a97c 400d34d8  
I/DEBUG   (  196):     41591cd4 4006cec5 4006ceed 4006ced9 4006cf01  
I/DEBUG   (  196):     41591ce4 40081490 40054b39 40081214 400bb919  
I/DEBUG   (  196):     41591cf4 400bb927 400d2b18 400d26b8 400d30b0  
I/DEBUG   (  196):     41591d04 4007f688 4007f708 4007f640 400858b9  
I/DEBUG   (  196):     41591d14 40099b29 400711ad 4006dca4 4006dab4  
I/DEBUG   (  196):     41591d24 4006dbb8 4009b19c 4006e020 4005451d  
I/DEBUG   (  196):     41591d34 4006e210 4006d890 400829cc 4027e53b  
I/DEBUG   (  196):     41591d44 40293c29 400bb919 40082001 40293c2d  
I/DEBUG   (  196): 
I/DEBUG   (  196): memory near fp:
I/DEBUG   (  196):     5bac122c 615e5000 5bac1128 61626ce4 5bac1350  
I/DEBUG   (  196):     5bac123c 5bab2fdc 00000001 615e5000 00000100  
I/DEBUG   (  196):     5bac124c 6362696c 65636e6f 732e6c61 0000006f  
I/DEBUG   (  196):     5bac125c 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     5bac126c 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     5bac127c 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     5bac128c 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     5bac129c 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     5bac12ac 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     5bac12bc 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     5bac12cc 6245c034 00000008 00000000 6245c000  
I/DEBUG   (  196):     5bac12dc 00105000 00000000 6255d9ec 00000000  
I/DEBUG   (  196):     5bac12ec 00000000 00000000 00000001 62468cd8  
I/DEBUG   (  196):     5bac12fc 6245c148 00000805 00000cb9 62478068  
I/DEBUG   (  196):     5bac130c 6247a07c 6255dec4 62488520 0000004c  
I/DEBUG   (  196):     5bac131c 6247d360 00001638 00000000 00000000  
I/DEBUG   (  196): 
I/DEBUG   (  196): memory near sp:
I/DEBUG   (  196):     bea050f8 00000000 00000000 bea05174 00000000  
I/DEBUG   (  196):     bea05108 00000000 00000000 00004000 91d84ebe  
I/DEBUG   (  196):     bea05118 00000006 00000016 00000f22 00000001  
I/DEBUG   (  196):     bea05128 00000001 4007229d 00000006 62539045  
I/DEBUG   (  196):     bea05138 00000000 400724b1 bea0514c 400711e5  
I/DEBUG   (  196):     bea05148 00000000 ffffffdf 400aa2c0 400aa224  
I/DEBUG   (  196):     bea05158 00000000 40073d97 415961f8 415961f8  
I/DEBUG   (  196):     bea05168 62539045 40080a90 00000000 4152bf4f  
I/DEBUG   (  196):     bea05178 bea05200 6c756e28 0000296c 00000000  
I/DEBUG   (  196):     bea05188 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     bea05198 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     bea051a8 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     bea051b8 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     bea051c8 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     bea051d8 00000000 00000000 00000000 00000000  
I/DEBUG   (  196):     bea051e8 00000000 00000000 00000000 00000000  
I/DEBUG   (  196): 
I/DEBUG   (  196): code around pc:
I/DEBUG   (  196):     400811b8 e8bd00f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  196):     400811c8 ea007025 e92d50f0 e3a07f43 ef000000  
I/DEBUG   (  196):     400811d8 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  196):     400811e8 ea00701d e92d50f0 e3a070ee ef000000  
I/DEBUG   (  196):     400811f8 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  196):     40081208 ea007015 e1520003 8a00008c f5d1f040  
I/DEBUG   (  196):     40081218 e92d4001 e3520010 3a000024 e2603000  
I/DEBUG   (  196):     40081228 e213300f 0a00000e e0422003 e1b0cf83  
I/DEBUG   (  196):     40081238 44d1e001 44c0e001 24d1c001 24d1e001  
I/DEBUG   (  196):     40081248 24c0c001 24c0e001 e1b0ce83 aa000001  
I/DEBUG   (  196):     40081258 f4a1030d f480031d 3a000001 f421070d  
I/DEBUG   (  196):     40081268 f400071d e2522040 3a000006 f421020d  
I/DEBUG   (  196):     40081278 f421420d f5d1f100 e2522040 f400022d  
I/DEBUG   (  196):     40081288 f400422d 2afffff8 e2922020 3a000002  
I/DEBUG   (  196):     40081298 f421020d e2422020 f400022d e2822020  
I/DEBUG   (  196):     400812a8 e3120010 0a000001 f4210a0d f4000a2d  
I/DEBUG   (  196): 
I/DEBUG   (  196): code around lr:
I/DEBUG   (  196):     4007227c 447b4b13 42b3e010 4812d10e 44786a1e  
I/DEBUG   (  196):     4007228c ec94f7fb e9d6f00d 46224631 ef98f00e  
I/DEBUG   (  196):     4007229c d00a3001 e00b2400 2b00681b 480ad1eb  
I/DEBUG   (  196):     400722ac 44782403 ec82f7fb f001e002 6804fa1b  
I/DEBUG   (  196):     400722bc fa18f001 46206005 bf00bd70 0003c12e  
I/DEBUG   (  196):     400722cc 0003c122 0003c11a 0003c0f6 bf7ef7ff  
I/DEBUG   (  196):     400722dc 43f0e92d 4a3d4b3c 589c447b 6823b08b  
I/DEBUG   (  196):     400722ec 460d4606 f0019309 46a1f9fd 8000f8d0  
I/DEBUG   (  196):     400722fc d0482d00 f00f4628 280ffe7d d8444604  
I/DEBUG   (  196):     4007230c ffe4f7ff d1064286 4629200f e8a0f00d  
I/DEBUG   (  196):     4007231c d03c2800 482ee02e f7fb4478 482debc6  
I/DEBUG   (  196):     4007232c e0154478 d11342b0 482b6a06 f7fb4478  
I/DEBUG   (  196):     4007233c 4a2aec3e 447a2120 a8014633 fab6f013  
I/DEBUG   (  196):     4007234c a8012101 fdb4f01a 46061c42 e011d104  
I/DEBUG   (  196):     4007235c 28006800 e02cd1e6 46294630 f0274622  
I/DEBUG   (  196):     4007236c 1c43fbdd d11e4607 f9bcf001 29046801  
```
Maybe it has something to do with ProGuard? I use [these rules](https://github.com/krschultz/android-proguard-snippets/blob/master/libraries/proguard-facebook-conceal.pro).

**Comment by helios175** [comment]
You are right, Pitel. It has to do with the proguard rule
(most of the time native code not finding a Java member has to do with that).

The annotation used changed packages.
So now the DoNotStrip annotation used lives in com.facebook.crypto.proguard.annotations.
If you change the rule file it should work.
