### ISSUE TITLE
Crash in LinuxPRNGSecureRandom

### ISSUE THREAD

**Issue by Pitel** [facebook/conceal#157]
Our app, using this library, started crashing on Android 4.1 (Lenovo A820) and 4.3 (Huawei G630) with the following root cause:

```
Caused by: java.lang.InstantiationException: can't instantiate class com.facebook.android.crypto.keychain.SecureRandomFix$LinuxPRNGSecureRandom; no empty constructor
```

**Comment by helios175** [comment]
Do you have a stacktrace?

I'm wondering if that's because that PRNG class is registered in the global Security registry and the default constructor is stripped away by proguard.

Mid-term we will provide a PRNG fix that doesn't need to register itself in that Security registry. So Java won't try to instantiate it.

Short-term: you could try adding an explicit no-args constructor to
SecureRandomFix.LinuxPRNGSecureRandom making sure it's not stripped by proguard:

import com.facebook.crypto.proguard.annotations.DoNotStrip;

In `SecureRandomFix.java`

```
....class LinuxPRNGSecureRandom...

@DoNotStrip
LinuxPRNGSecureRandom() {
}
```

**Comment by Pitel** [comment]
There is the whole stacktrace:
```
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.master.lois/cz.master.annie.ui.landingpage.ActivityMain}: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216)
    at android.app.ActivityThread.access$600(ActivityThread.java:149)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5022)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
    at java.security.SecureRandom.<init>(SecureRandom.java:102)
    at cz.master.annie.networking.rest.HttpsTrustManager.allowAllSSL(HttpsTrustManager.java:39)
    at cz.master.annie.ui.landingpage.ActivityMain.onCreate(ActivityMain.java:188)
    at android.app.Activity.performCreate(Activity.java:5032)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216) 
    at android.app.ActivityThread.access$600(ActivityThread.java:149) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:153) 
    at android.app.ActivityThread.main(ActivityThread.java:5022) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790) 
    at dalvik.system.NativeStart.main(Native Method) 
 Caused by: java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
    at java.security.Provider$Service.newInstance(Provider.java:991)
    at java.security.SecureRandom.<init>(SecureRandom.java:99)
    at cz.master.annie.networking.rest.HttpsTrustManager.allowAllSSL(HttpsTrustManager.java:39) 
    at cz.master.annie.ui.landingpage.ActivityMain.onCreate(ActivityMain.java:188) 
    at android.app.Activity.performCreate(Activity.java:5032) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216) 
    at android.app.ActivityThread.access$600(ActivityThread.java:149) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:153) 
    at android.app.ActivityThread.main(ActivityThread.java:5022) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790) 
    at dalvik.system.NativeStart.main(Native Method) 
 Caused by: java.lang.InstantiationException: can't instantiate class com.facebook.android.crypto.keychain.SecureRandomFix$LinuxPRNGSecureRandom; no empty constructor
    at java.lang.Class.newInstanceImpl(Native Method)
    at java.lang.Class.newInstance(Class.java:1319)
    at java.security.Provider$Service.newInstance(Provider.java:989)
    at java.security.SecureRandom.<init>(SecureRandom.java:99) 
    at cz.master.annie.networking.rest.HttpsTrustManager.allowAllSSL(HttpsTrustManager.java:39) 
    at cz.master.annie.ui.landingpage.ActivityMain.onCreate(ActivityMain.java:188) 
    at android.app.Activity.performCreate(Activity.java:5032) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2216) 
    at android.app.ActivityThread.access$600(ActivityThread.java:149) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:153) 
    at android.app.ActivityThread.main(ActivityThread.java:5022) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1032) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790) 
    at dalvik.system.NativeStart.main(Native Method) 
```

The `HttpsTrustManager.java:39` is
```java
final SSLContext context = SSLContext.getInstance("TLS"); //38
context.init(null, trustManagers, new SecureRandom()); //39
```

I doubt it's ProGuard problem, because it happens in debug build where ProGuard is disabled.

**Comment by helios175** [comment]
Sorry about the delay.

The PRNG works by registering the provider in the system, and the provider has the class name for the LinuxPRNGSecureRandom itself. That's the class that cannot be instantiated because of the lack of an empty constructor.

I'm a little confused because it doesn't explicitely declare any contructor, nor the parent class SecureRandomSpi. Unless the system libraries for that particular phone/OS declare some non-empty constructor. Or the empty constructor is not public. Weird.

In the long term I want to provide another solution that doesn't imply registering a general provider. That will also mean that we don't need any instantiation from the system. Conceal will do it itself.

But for now and for debugging this I would add an explicit empty constructor. That should:
1) offer it explicitely so it *should* be found
2) test at compile time if the parent class has a default constructor or what (even if protected)

I will create a branch for this and send you the link. But it's very simple.

**Comment by helios175** [comment]
Check https://github.com/facebook/conceal/tree/emptyconstructor

**Comment by Pitel** [comment]
I'll need a little help with this. I did `buck build :conceal_android`, where can I now find some jar/aar output to use in my project?

**Comment by Sphinx1111** [comment]
I see on stackoverflow you have had the IOException problem about unexpected crypto version -1, you later resolved?

**Comment by Pitel** [comment]
We've limited `minSdkVersion` to 19.

Btw, I'm still willing to help resolve it, but I still need help with building.

**Comment by helios175** [comment]
I had an empty constructor pending for merge into master branch.
Also master branch has also a new system for random generators that doesn't register any provider. I bet that would solve the issue as there's no way the system tries to create that object itself.

Nevertheless I will have both (empty constructor + no provider registering) and generate a version you can download.

Generally we have our projects all configured with BUCK and define the dependency on this one, so all the application gets built with buck at once.

For generating the AARs I use gradle (in fact I use old gradle 2.2 because some plugin needs that version).

**Comment by Pitel** [comment]
Good news. Can we expect new version soon?
