### ISSUE TITLE
Native Crash!!!

### ISSUE THREAD

**Issue by CarlTien** [facebook/conceal#186]
11-23 19:03:46.031 8312-8312/com.ecitic.creditcard.app I/art: Thread[1,tid=8312,Native,Thread*=0x777f4a1a00,peer=0x78b4add0,"main"] recursive attempt to load library "/data/app/com.ecitic.creditcard.app-2/lib/arm64/libfb.so"
11-23 19:03:46.034 8312-8312/com.ecitic.creditcard.app A/fbassert: Assert (/Users/heliosalonso/github/facebook/conceal/first-party/fbjni/native/fb/jni/Exceptions.cpp:308): ptr
11-23 19:03:46.035 8312-8312/com.ecitic.creditcard.app A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadb00c in tid 8312 (.creditcard.app)
                                                               
                                                               [ 11-23 19:03:46.037   389:  389 W/         ]
                                                               debuggerd: handling request: pid=8312 uid=10151 gid=10151 tid=8312

**Comment by CarlTien** [comment]
How can I avoid the app crash ? why use assert to force app crash?

**Comment by CarlTien** [comment]
please help

**Comment by helios175** [comment]
SIGSEGV is when you access memory outside the bounds. I'm thinking maybe you are passing a 16 bytes key (128 bits) to a 32 bytes (256 bits) cipher. I should have added a check on the Java side to throw an exception. I will fix that.

So action items:
- you: check what kind of keychain are you passing (in Conceal 2, the constructor receives a CryptoConfig to indicate the desired size. Use KEY_256 if you're using the default/256 bits.
- me: I will add a fix so the Java code checks the sizes of the Crypto and the provided KeyChain match.

**Comment by hereisderek** [comment]
well, I have the exact same issue

**Comment by childnode** [comment]
well, I can share some logs too for this ;/
using conceal 2.0.1 and the proguard rules from https://raw.githubusercontent.com/facebook/conceal/v2.0.1/proguard_annotations.pro

I'm going forward to check why this fails newer days after updating build tools and targetSDKLevel resp. which change caused this to fail

```
2019-02-22 10:25:34.571 4257-4257/? E/zygote64: Failed to register native method com.facebook.cipher.jni.CipherHybrid.initHybrid(BLcom/facebook/crypto/keychain/KeyChain;)Lcom/facebook/jni/HybridData; in /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/base.apk
2019-02-22 10:25:34.575 4257-4257/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4257 (my.app)
2019-02-22 10:25:34.652 4516-4516/? A/DEBUG: pid: 4257, tid: 4257, name: my.app  >>> my.app <<<
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #02 pc 0000000000074e24  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libconcealjni.so
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #03 pc 000000000003f170  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libconcealjni.so
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #04 pc 000000000005b200  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libfb.so
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #05 pc 000000000005b708  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libfb.so
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #06 pc 0000000000011ab4  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libfb.so (_ZN8facebook3jni38throwPendingJniExceptionAsCppExceptionEv+284)
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #07 pc 000000000001c71c  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libconcealjni.so
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #08 pc 0000000000023c44  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libconcealjni.so
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #09 pc 000000000001973c  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libfb.so (_ZN8facebook3jni10initializeEP7_JavaVMOSt8functionIFvvEE+328)
2019-02-22 10:25:34.732 4516-4516/? A/DEBUG:     #10 pc 0000000000023d28  /data/app/my.app-DqbKB97Wrdt7XNapUVyraA==/lib/arm64/libconcealjni.so (JNI_OnLoad+92)
2019-02-22 10:25:35.470 4595-4595/? E/audit: type=1701 audit(1550827535.465:23172): auid=4294967295 uid=10421 gid=10421 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=4257 comm="my.app" exe="/system/bin/app_process64" sig=6
```
```
2019-02-22 09:22:08.121 22313-22313/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app, PID: 22313
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfb.so
        at com.facebook.d.k.b(Unknown Source:138)
        at com.facebook.d.k.a(Unknown Source:53)
        at com.facebook.d.k.a(Unknown Source:1)
        at com.facebook.d.i.b(Unknown Source:34)
        at com.facebook.d.i.c(Unknown Source:0)
        at com.facebook.a.a.a.b.a(Unknown Source:1)
        at com.facebook.cipher.a.a(Unknown Source:2)
        at com.facebook.b.c.a(Unknown Source:3)
        at my.app.a.b.a(Unknown Source:22)
        at my.app.a.b.b(Unknown Source:17)
        at my.app.a.a.b(Unknown Source:0)
        at my.app.a.a.a(Unknown Source:7)
        at my.app.a.d.a(Unknown Source:2)
        at my.app.onActivityResult(Unknown Source:18)
        at android.app.Activity.dispatchActivityResult(Activity.java:7556)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by KonsKin** [comment]
Same error here. Using 2.0.2

**Comment by nEdAy** [comment]
where is 2.0.2

**Comment by barnhill** [comment]
Similar error when trying to use app bundles in Android apps
