### ISSUE TITLE
showing NoSuchMethodException on Android P when initialing the SoLoader

### ISSUE THREAD

**Issue by kaiyan910** [facebook/conceal#197]
```
java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
at java.lang.Class.getMethod(Class.java:2068)
at java.lang.Class.getDeclaredMethod(Class.java:2047)
at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:297)
at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:249)
at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:156)
at com.facebook.soloader.SoLoader.init(SoLoader.java:131)
at com.facebook.soloader.SoLoader.init(SoLoader.java:115)
at com.facebook.soloader.SoLoader.init(SoLoader.java:142)
```

I think it is the same issue as 
https://github.com/facebook/fresco/issues/2115 ?

**Comment by geekyprateek** [comment]
@siyengar is there any plan to update the library for the same issue, we are using the lib heavily and now we are stuck on this. TIA

**Comment by bmbariah** [comment]
Same fix as this one? : https://github.com/facebook/SoLoader/commit/3d691395dd353d7ebf633db445bcc7460232aa7a

**Comment by roadhouse-dev** [comment]
We are also stuck on this.

**Comment by ysoftware** [comment]
This has to be fixed.

**Comment by roadhouse-dev** [comment]
Can you please clarify where you are from?

On 1 Feb. 2019 9:56 pm, Yaroslav Erohin <notifications@github.com> wrote:

This has to be fixed.

**Comment by idish** [comment]
This must be fixed ASAP! VERY CRITICAL ISSUE!

**Comment by mandrachek** [comment]
I thought we might be able to work around this issue by overriding the version of SoLoader conceal uses by specifying the 0.6.0 version (or presumably later), e.g.

```
    implementation 'com.facebook.conceal:conceal:2.0.2@aar'
    implementation 'com.facebook.soloader:soloader:0.6.0'
```

But it doesn't work:
Error: Program type already present: com.facebook.soloader.[SomeClass]

**Comment by kaiyan910** [comment]
it won't work as conceal's soloader is packed inside the library, not from gradle dependency.

**Comment by mandrachek** [comment]
Yeah, figured that out. Can't stand buck.  I'm dropping this lib like a hot potato.  It's pretty much abandoned.

**Comment by childnode** [comment]
is this s.th. that caused #186 ?!

**Comment by goemic** [comment]
Is this bug simply ignored??

I really would like to integrate this library but I'm scared to use it in production since nobody seems to care about this bug or even takes a look at the pull request.

Does anyone have a custom build of conceal where the source set is replaced by the corresponding gradle depency for soloader?
